binance:
  apiKey: ${api-key}
  secret: ${secret}

spring:
  datasource:
    url: ${db_url}
    username: ${db_user}
    password: ${db_password}
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: ${user}
      password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

telegram:
  token: ${token}
  chatId: ${chatId}
  scheduler: ${scheduler}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: ${actuatorPort}
  endpoint:
    health:
      show-details: always

info:
  version: '@project.version@'