binance:
  apiKey: ${api-key}
  secret: ${secret}

spring:
  security:
    user:
      name: ${user}
      password: ${password}

telegram:
  token: ${token}
  chatId: ${chatId}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8081
  endpoint:
    health:
      show-details: always

info:
  version: @version@